// Exports the ACTIVE stories table from stories.db into shared/storiesData.js —
// the bundled data the app serves at runtime (reliable on Vercel, no DB engine
// or API needed). Run after seeding or after a content swap:
//     node backend/db/export.js
//
// STAGE-6 SWAP: change ACTIVE_TABLE to 'stories_v2', re-run this, then deploy.
import { DatabaseSync } from 'node:sqlite'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { writeFileSync } from 'node:fs'

const ACTIVE_TABLE = 'stories' // ← the live story set. Change to 'stories_v2' at Stage 6.

const __dirname = dirname(fileURLToPath(import.meta.url))
const dbPath = join(__dirname, 'stories.db')
const outPath = join(__dirname, '../../shared/storiesData.js')

const db = new DatabaseSync(dbPath, { readOnly: true })
const storyRows = db.prepare(
  `SELECT subject_key, subject, category, age_group, language, title, body, moral
     FROM "${ACTIVE_TABLE}" ORDER BY id`
).all()
const itemRows = db.prepare(
  `SELECT key, term, term_hi, category FROM search_items ORDER BY id`
).all()
db.close()

const STORIES = storyRows.map((r) => ({
  subjectKey: r.subject_key,
  subject: r.subject,
  category: r.category,
  ageGroup: r.age_group,
  language: r.language,
  title: r.title,
  body: r.body,
  moral: r.moral,
}))
const SEARCH_ITEMS = itemRows.map((r) => ({ key: r.key, term: r.term, term_hi: r.term_hi, category: r.category }))

const out =
  `// ⚠️ AUTO-GENERATED by backend/db/export.js from the "${ACTIVE_TABLE}" table.\n` +
  `// Do not edit by hand. Regenerate with: node backend/db/export.js\n\n` +
  `export const META = ${JSON.stringify({ activeTable: ACTIVE_TABLE, stories: STORIES.length, searchItems: SEARCH_ITEMS.length })}\n\n` +
  `export const STORIES = ${JSON.stringify(STORIES)}\n\n` +
  `export const SEARCH_ITEMS = ${JSON.stringify(SEARCH_ITEMS)}\n`

writeFileSync(outPath, out)
console.log(`Exported ${STORIES.length} stories + ${SEARCH_ITEMS.length} search items from "${ACTIVE_TABLE}" -> shared/storiesData.js`)
